# Generated by Django 4.2.1 on 2023-08-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedad',
            options={'ordering': ('id', reversed), 'verbose_name': 'novedadad', 'verbose_name_plural': 'novedadades'},
        ),
    ]
