# Generated by Django 4.2.1 on 2023-08-19 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_alter_novedad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedad',
            options={'ordering': ['id'], 'verbose_name': 'novedadad', 'verbose_name_plural': 'novedadades'},
        ),
        migrations.AddField(
            model_name='novedad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
